/* =====================================================
   MUNTAHA PORTFOLIO — script.js
   All interactions, animations, dynamic project system
   ===================================================== */

"use strict";

/* =====================================================
   ▸ PROJECT DATA — ADD / EDIT YOUR PROJECTS HERE
   ===================================================== */
const projects = [
  {
    title: "AI Portfolio Website",
    tag: "Portfolio · Web",
    description: "Modern AI-based personal portfolio with smooth animations, glassmorphism UI, and dynamic project system built to showcase creative and technical expertise.",
    fullDescription: "A fully animated, dark-themed portfolio website designed to showcase Generative AI capabilities and personal brand. Built with pure HTML, CSS, and JavaScript — no frameworks, no bloat. Features include a custom cursor, scroll-triggered reveals, typing animations, interactive skill bars, and a dynamic project modal system.",
    image: "project1.jpg",
    placeholder: "🌐",
    placeholderBg: "pg-1",
    features: [
      "Custom cursor with lag-follow ring and hover scaling effects",
      "Scroll-triggered fade and slide-in reveal animations",
      "Typing animation with multiple rotating text strings",
      "Dynamic project system — add new projects via JavaScript array",
      "Glassmorphism card design with animated neon orbs",
      "Fully responsive across mobile, tablet, and desktop",
      "Sticky blurred navbar with scroll-state transition",
      "Contact form with client-side validation and success state"
    ],
    tech: ["HTML5", "CSS3", "JavaScript", "Glassmorphism", "CSS Animations"],
    liveLink: "https://sheikhsiddique722-sketch.github.io/futureself-ai-mirror/",
  },
  {
    title: "Biryani Website",
    tag: "Food · UI Design",
    description: "Beautiful food ordering website UI concept with an immersive menu experience, smooth transitions, and mouth-watering visual design.",
    fullDescription: "A concept food ordering website for a premium Biryani restaurant brand. Designed with a focus on visual storytelling — warm imagery, rich typography, and smooth page transitions that make the ordering experience feel as good as the food itself. The layout is optimised for high conversion with a clear visual hierarchy guiding users from exploration to order.",
    image: "project2.jpg",
    placeholder: "🍛",
    placeholderBg: "pg-4",
    features: [
      "Immersive hero section with full-bleed food photography",
      "Interactive menu category filtering with smooth transitions",
      "Cart UI with animated add-to-cart feedback",
      "Responsive grid layout for menu items with hover zoom effects",
      "Sticky order summary sidebar on desktop",
      "Mobile-first design with swipeable menu cards"
    ],
    tech: ["HTML5", "CSS3", "Flexbox", "Grid", "CSS Transitions"],
    liveLink: "https://sheikhsiddique722-sketch.github.io/biryani-restaurant/",
  },
  {
    title: "FutureSelf AI Mirror",
    tag: "AI Experience · Interactive",
    description: "An immersive AI-powered experience that generates a personalised vision of your future self through reflective prompts and generative imagery.",
    fullDescription: "FutureSelf AI Mirror is a reflective, AI-driven experience designed to help users visualise their most aspirational self. By combining carefully engineered prompts with generative imagery and narrative storytelling, this project creates a deeply personal encounter with possibility. The experience uses layered context-setting and structured input to coax language models toward highly personalised, emotionally resonant outputs.",
    image: "project3.jpg",
    placeholder: "🪞",
    placeholderBg: "pg-2",
    features: [
      "Multi-stage reflective prompt pipeline with context chaining",
      "Dynamic Midjourney prompt construction based on user input",
      "Personalised narrative letter generated by AI as the user's future self",
      "Tone calibration layer for aspirational vs. grounded responses",
      "Iterative refinement — regenerate specific elements without restarting",
      "Intimate, non-chatbot UI that feels like a personal reveal"
    ],
    tech: ["Prompt Engineering", "GPT-4", "Midjourney", "HTML/CSS/JS", "UX Design"],
    liveLink: "https://sheikhsiddique722-sketch.github.io/futureself-ai-mirror/",
  },
];
/* ===================================================== */


/* --------- CUSTOM CURSOR --------- */
const cursorDot = document.getElementById('cursorDot');
const cursorRing = document.getElementById('cursorRing');
let mouseX = 0, mouseY = 0, ringX = 0, ringY = 0;

if (cursorDot && cursorRing) {
  document.addEventListener('mousemove', e => {
    mouseX = e.clientX;
    mouseY = e.clientY;
    cursorDot.style.left = mouseX + 'px';
    cursorDot.style.top = mouseY + 'px';
  });

  function animateRing() {
    ringX += (mouseX - ringX) * 0.12;
    ringY += (mouseY - ringY) * 0.12;
    cursorRing.style.left = ringX + 'px';
    cursorRing.style.top = ringY + 'px';
    requestAnimationFrame(animateRing);
  }
  animateRing();

  document.querySelectorAll('a, button, .project-card, .tool-chip, .about-info-card').forEach(el => {
    el.addEventListener('mouseenter', () => cursorRing.classList.add('hovered'));
    el.addEventListener('mouseleave', () => cursorRing.classList.remove('hovered'));
  });
}


/* --------- NAVBAR SCROLL --------- */
const navbar = document.getElementById('navbar');
window.addEventListener('scroll', () => {
  if (navbar) navbar.classList.toggle('scrolled', window.scrollY > 40);
}, { passive: true });


/* --------- HAMBURGER MENU --------- */
const hamburger = document.getElementById('hamburger');
const navLinks = document.getElementById('navLinks');

if (hamburger && navLinks) {
  hamburger.addEventListener('click', () => {
    hamburger.classList.toggle('open');
    navLinks.classList.toggle('open');
  });
  navLinks.querySelectorAll('a').forEach(link => {
    link.addEventListener('click', () => {
      hamburger.classList.remove('open');
      navLinks.classList.remove('open');
    });
  });
}


/* --------- TYPING ANIMATION --------- */
const typingStrings = [
  "I build AI-powered solutions",
  "I design modern websites",
  "I craft intelligent prompts",
  "I turn ideas into reality"
];
let typeIdx = 0, charIdx = 0, isDeleting = false;
const typedEl = document.getElementById('typedText');

function type() {
  if (!typedEl) return;
  const current = typingStrings[typeIdx];
  if (isDeleting) {
    typedEl.textContent = current.substring(0, charIdx--);
    if (charIdx < 0) { isDeleting = false; typeIdx = (typeIdx + 1) % typingStrings.length; charIdx = 0; setTimeout(type, 500); return; }
    setTimeout(type, 40);
  } else {
    typedEl.textContent = current.substring(0, charIdx++);
    if (charIdx > current.length) { isDeleting = true; setTimeout(type, 2000); return; }
    setTimeout(type, 65);
  }
}
setTimeout(type, 1000);


/* --------- SCROLL REVEAL --------- */
const revealEls = document.querySelectorAll('.reveal');
const revealObs = new IntersectionObserver(entries => {
  entries.forEach(e => { if (e.isIntersecting) { e.target.classList.add('visible'); revealObs.unobserve(e.target); } });
}, { threshold: 0.1 });
revealEls.forEach(el => revealObs.observe(el));


/* --------- SKILL BARS --------- */
const skillCards = document.querySelectorAll('.skill-item');
const barObs = new IntersectionObserver(entries => {
  entries.forEach(e => {
    if (e.isIntersecting) {
      const fill = e.target.querySelector('.skill-bar-fill');
      if (fill) fill.style.width = fill.dataset.width + '%';
      barObs.unobserve(e.target);
    }
  });
}, { threshold: 0.3 });
skillCards.forEach(c => barObs.observe(c));


/* --------- RENDER PROJECT CARDS --------- */
function renderProjectCards() {
  const grid = document.getElementById('projectsGrid');
  if (!grid) return;

  projects.forEach((p, i) => {
    const card = document.createElement('div');
    card.className = 'project-card reveal' + (i > 0 ? ' reveal-delay-' + Math.min(i, 3) : '');
    card.innerHTML = `
      <div class="project-num-badge">${String(i + 1).padStart(2, '0')}</div>
      <div class="project-card-img-placeholder ${p.placeholderBg}" style="height:200px;padding:0;overflow:hidden;position:relative;">
        <img class="project-screenshot" data-url="${p.liveLink}" alt="${p.title}" style="width:100%;height:100%;object-fit:cover;display:none;"/>
        <span class="project-emoji-fallback" style="font-size:3.5rem;opacity:0.5;display:flex;width:100%;height:100%;align-items:center;justify-content:center;">${p.placeholder}</span>
        <div class="project-card-gradient-overlay"></div>
      </div>
      <div class="project-card-body">
        <div class="project-card-tag">${p.tag}</div>
        <h3 class="project-card-title">${p.title}</h3>
        <p class="project-card-desc">${p.description}</p>
        <div class="project-card-tech">
          ${p.tech.map(t => `<span class="tech-tag">${t}</span>`).join('')}
        </div>
        <button class="project-card-action" aria-label="View details for ${p.title}">
          View Details
          <svg width="14" height="14" viewBox="0 0 14 14" fill="none"><path d="M2.5 7h9M8 3.5 11.5 7 8 10.5" stroke="currentColor" stroke-width="1.3" stroke-linecap="round" stroke-linejoin="round"/></svg>
        </button>
      </div>
    `;
    card.addEventListener('click', () => openModal(i));
    grid.appendChild(card);
  });

  /* Re-observe newly added reveal elements */
  document.querySelectorAll('.reveal:not([data-observed])').forEach(el => {
    el.setAttribute('data-observed', '1');
    revealObs.observe(el);
  });
}
renderProjectCards();


/* --------- PROJECT MODAL --------- */
const modalOverlay = document.getElementById('modalOverlay');
const modalContent = document.getElementById('modalContent');
const modalClose = document.getElementById('modalClose');

function openModal(idx) {
  const p = projects[idx];
  if (!p || !modalOverlay || !modalContent) return;

  modalContent.innerHTML = `
    <div class="modal-img-placeholder ${p.placeholderBg}" style="padding:0;overflow:hidden;position:relative;">
      <img class="project-screenshot" data-url="${p.liveLink}" alt="${p.title}" style="width:100%;height:100%;object-fit:cover;display:none;"/>
      <span class="project-emoji-fallback" style="font-size:5rem;opacity:0.35;display:flex;width:100%;height:100%;align-items:center;justify-content:center;">${p.placeholder}</span>
    </div>
    <div class="modal-body">
      <div class="modal-meta">
        <span class="modal-tag">${p.tag}</span>
      </div>
      <h2 class="modal-title">${p.title}</h2>
      <p class="modal-desc">${p.fullDescription}</p>

      <div class="modal-features-heading">// Key Features</div>
      <ul class="modal-features">
        ${p.features.map(f => `<li>${f}</li>`).join('')}
      </ul>

      <div class="modal-tech-heading">// Tech Stack</div>
      <div class="modal-tech-wrap">
        ${p.tech.map(t => `<span class="tech-tag">${t}</span>`).join('')}
      </div>

      <div class="modal-actions">
        <a href="${p.liveLink}" class="btn btn-primary" target="_blank" rel="noopener">
          <span>Live Project</span>
          <svg width="14" height="14" viewBox="0 0 14 14" fill="none"><path d="M8.5 2H12v3.5M12 2 6 8M3 4H2a1 1 0 00-1 1v7a1 1 0 001 1h7a1 1 0 001-1v-1" stroke="currentColor" stroke-width="1.3" stroke-linecap="round" stroke-linejoin="round"/></svg>
        </a>
      </div>
    </div>
  `;

  modalOverlay.classList.add('open');
  document.body.style.overflow = 'hidden';
}

function closeModal() {
  if (!modalOverlay) return;
  modalOverlay.classList.remove('open');
  document.body.style.overflow = '';
}

if (modalClose) modalClose.addEventListener('click', closeModal);
if (modalOverlay) {
  modalOverlay.addEventListener('click', e => {
    if (e.target === modalOverlay) closeModal();
  });
}
document.addEventListener('keydown', e => { if (e.key === 'Escape') closeModal(); });


/* --------- CONTACT FORM --------- */
const contactForm = document.getElementById('contactForm');
const formSuccess = document.getElementById('formSuccess');

if (contactForm) {
  contactForm.addEventListener('submit', e => {
    e.preventDefault();
    const btn = contactForm.querySelector('button[type="submit"]');
    if (btn) { btn.textContent = 'Sending...'; btn.disabled = true; }
    setTimeout(() => {
      contactForm.reset();
      if (btn) { btn.innerHTML = '<span>Send Message</span>'; btn.disabled = false; }
      if (formSuccess) formSuccess.classList.add('show');
      setTimeout(() => { if (formSuccess) formSuccess.classList.remove('show'); }, 5000);
    }, 1200);
  });
}


/* --------- SMOOTH ANCHOR SCROLL --------- */
document.querySelectorAll('a[href^="#"]').forEach(anchor => {
  anchor.addEventListener('click', e => {
    const target = document.querySelector(anchor.getAttribute('href'));
    if (target) {
      e.preventDefault();
      const offset = document.getElementById('navbar')?.offsetHeight || 72;
      window.scrollTo({ top: target.offsetTop - offset, behavior: 'smooth' });
    }
  });
});


/* --------- PROJECT SCREENSHOTS --------- */
function loadScreenshots() {
  document.querySelectorAll('.project-screenshot[data-url]').forEach(img => {
    const url = img.dataset.url;
    if (!url || url === '#') return;
    fetch(`https://api.microlink.io/?url=${encodeURIComponent(url)}&screenshot=true&meta=false`)
      .then(r => r.json())
      .then(data => {
        const screenshotUrl = data?.data?.screenshot?.url;
        if (screenshotUrl) {
          img.src = screenshotUrl;
          img.style.display = 'block';
          const fallback = img.nextElementSibling;
          if (fallback) fallback.style.display = 'none';
        }
      })
      .catch(() => {});
  });
}

const screenshotObs = new MutationObserver(() => loadScreenshots());
screenshotObs.observe(document.body, { childList: true, subtree: true });
loadScreenshots();


/* --------- PARALLAX HERO ORBS --------- */
window.addEventListener('scroll', () => {
  const scrollY = window.scrollY;
  const orb1 = document.querySelector('.orb-1');
  const orb2 = document.querySelector('.orb-2');
  if (orb1) orb1.style.transform = `translateY(${scrollY * 0.15}px)`;
  if (orb2) orb2.style.transform = `translateY(${-scrollY * 0.1}px)`;
}, { passive: true });